# Generated by Django 5.0.1 on 2024-04-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='departure_airport',
            new_name='departure_city',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_airport',
            new_name='destination_city',
        ),
    ]
